### ISSUE TITLE
KW2.0 - I18n网站国际化

### ISSUE THREAD

**Issue by ouyc** [tatfook/KWPM#13]
Paracraft课程教学已经通过审核，进入美国MAP3教育。keepwork需要支持海外教学，因此也需要支持英文版本。

**Comment by azothli** [comment]
国际版差异化内容：
注册：去除手机注册，增加海外常用的账号：fb......
登录接口对应注册调整
实名制去除
用户年龄统计（是否需要进行少儿保护?）国外法律的问题
关键字系统（保留系统，清空国内内容）
付费渠道（按照国外需要调整接入）
其他公司信息、联系、客服等内容的对应调整
